### ISSUE TITLE
Status Update causes Connection refused - connect(2) for "localhost" port 25

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/schedule_gardener#100]
On Production this problem does not exist
On master 
1 Sign in as gardener (me)
2 Go to calendar
3 Click on a past appointment 
4 In edit change status  booked to completed or not completed
5 Connection refused - connect(2) for "localhost" port 25

**Comment by RichardWigley** [comment]
Email refactored and feature added
Development: Uses letter_opener
Test: Minimum to pass
Staging: Removed email for now - see how it goes
Production: Refactoring config but code not changed.

https://github.com/BCS-io/schedule_gardener/commit/848c622161421ce9baa3dd3f808954f01dd87654

**Comment by MargaretLangley** [comment]
Checked : fixed ok
