### ISSUE TITLE
When creating an appointment, cancel button stops update 

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/schedule_gardener#103]
Cancel button stops update. 
Is this clear for clients?
Should we have a delete button?

**Comment by RichardWigley** [comment]
Lets follow the Google calendar and have ....

| Primary Action | ----| Discard Changes |---| Delete |

I think the primary button should be the most obvious to press....
Any convention used should be the same throughout the application.

**Comment by MargaretLangley** [comment]
Commit 40dcd33 made buttons & their usage more obvious for user. Buttons were down to 2 on a form. Deletion being available on a different page.
