### ISSUE TITLE
Checkbox should be on the left had side

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/schedule_gardener#109]
Checkbox form elements should have the checkbox to the left of the text. 

see appointment/form and contact/form

Decide if we remove bootstrap before looking at it as Simpleform-bootstrap requires special code. 

Example of changing simple form
http://stackoverflow.com/questions/13656819/simple-form-with-bootstrap-check-box

Example of bootstrap and simple form
https://github.com/plataformatec/simple_form/issues/670

Think there is help page in wiki on this issue.

**Comment by RichardWigley** [comment]
FIX https://github.com/BCS-io/schedule_gardener/commit/9a943104e4612a9b607306b802c82404af934645
