### ISSUE TITLE
Password Reset: No email sent to client on first sign in

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/schedule_gardener#113]
Go to sign in page
Go to forgotten password page
Git email address as tglangley@gmail.com
Message comes back that email has been sent.
Go to gmail
NO MESSAGE

**Comment by RichardWigley** [comment]
https://github.com/BCS-io/schedule_gardener/commit/2f453d61e1cac0b33768e79c22270edabdfd86f6
