### ISSUE TITLE
Masquerading needs to be clearer and should not allow you to signout as the masked-user

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/schedule_gardener#51]
### Masquerading Issues
1 While masquerading put in a large red  'mask' button on menu bar
   - clicking the button stops masquerading

2 You cannot sign out as masquerade user. 
   * White masquerading - the user menu in the nav bar does not let you sign out

**Comment by RichardWigley** [comment]
fixed here

https://github.com/BCS-io/schedule_gardener/commit/069818381e1b5370bc8986ea766eaf60c1bec082
