### ISSUE TITLE
Weekend colours cannot be set in CSS

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/schedule_gardener#65]
The weekend colours on the calendar cannot be set because of css specificity rules are a PITA. Look at the code to simplify, ideally, but regardless sort out a way of setting the weekend colours.

Today styling disappears at the weekend.

**Comment by RichardWigley** [comment]
CSS simplified - try this version
https://github.com/BCS-io/schedule_gardener/commit/6cc981797308b707f5d64aaf5f21fe68dacd5d86
