### ISSUE TITLE
Masquerade goes straight to sign in.

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/schedule_gardener#99]
Login as admin
Go to users page.
Choose a user & click on masquerade button
Page changes to sign in
Last pass  puts my signin details in 
I am then signed in as Margaret....

I see code does send to sign in, but does not allow for last pass overwrite.
Maybe a second signin page, not allowing last pass to overwrite?

**Comment by RichardWigley** [comment]
masquarade was redirecting to home page - everything was working except the page it left you on.

Fix https://github.com/BCS-io/schedule_gardener/commit/7aacab66f7f62e4e16468a9a532330e8e1d54bf8

**Comment by MargaretLangley** [comment]
Fix ok
